/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ['class'],
    content: ['./pages/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
    theme: {
        container: {
            center: true,
            padding: 'var(--spacing-xl)',
            screens: {
                '2xl': '1400px',
            },
        },
        extend: {
            fontFamily: {
                sans: ['var(--font-crimson-text)'],
                serif: ['var(--font-crimson-text)'],
                dancing: ['var(--font-dancing-script)'],
            },
            aspectRatio: {
                artists: 'var(--aspect-artists)',
                shorts: 'var(--aspect-shorts)',
                news: 'var(--aspect-news)',
                profile: 'var(--aspect-profile)',
                video: 'var(--aspect-video)',
            },
            colors: {
                // Legacy compatibility
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                // New design system colors
                bg: {
                    DEFAULT: 'hsl(var(--color-background))',
                    alt: 'hsl(var(--color-background-alt))',
                    dark: 'hsl(var(--color-background-dark))',
                    darker: 'hsl(var(--color-background-darker))',
                },
                text: {
                    primary: 'hsl(var(--color-text-primary))',
                    secondary: 'hsl(var(--color-text-secondary))',
                    light: 'hsl(var(--color-text-light))',
                    white: 'hsl(var(--color-text-white))',
                },
                orange: {
                    accent: 'hsl(var(--color-accent-orange))',
                    'accent-dark': 'hsl(var(--color-accent-orange-dark))',
                },
            },
            spacing: {
                'xs': 'var(--spacing-xs)',
                'sm': 'var(--spacing-sm)',
                'md': 'var(--spacing-md)',
                'lg': 'var(--spacing-lg)',
                'xl': 'var(--spacing-xl)',
                '2xl': 'var(--spacing-2xl)',
                '3xl': 'var(--spacing-3xl)',
                '4xl': 'var(--spacing-4xl)',
                '5xl': 'var(--spacing-5xl)',
                '6xl': 'var(--spacing-6xl)',
                'header': 'var(--spacing-header)',
                'section': 'var(--spacing-section)',
                'section-lg': 'var(--spacing-section-lg)',
            },
            fontSize: {
                'xs': ['var(--font-size-xs)', { lineHeight: 'var(--line-height-normal)' }],
                'sm': ['var(--font-size-sm)', { lineHeight: 'var(--line-height-normal)' }],
                'base-sm': ['var(--font-size-base-sm)', { lineHeight: 'var(--line-height-normal)' }],
                'base': ['var(--font-size-base)', { lineHeight: 'var(--line-height-normal)' }],
                'md': ['var(--font-size-md)', { lineHeight: 'var(--line-height-normal)' }],
                'lg': ['var(--font-size-lg)', { lineHeight: 'var(--line-height-normal)' }],
                'xl': ['var(--font-size-xl)', { lineHeight: 'var(--line-height-normal)' }],
                '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-tight)' }],
                '3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-tight)' }],
                '4xl': ['var(--font-size-4xl)', { lineHeight: 'var(--line-height-tight)' }],
                '5xl': ['var(--font-size-5xl)', { lineHeight: 'var(--line-height-tight)' }],
                '6xl': ['var(--font-size-6xl)', { lineHeight: 'var(--line-height-none)' }],
                '7xl': ['var(--font-size-7xl)', { lineHeight: 'var(--line-height-none)' }],
                '8xl': ['var(--font-size-8xl)', { lineHeight: 'var(--line-height-none)' }],
                'hero-mobile': ['var(--font-size-hero-mobile)', { lineHeight: 'var(--line-height-none)' }],
                'hero-desktop': ['var(--font-size-hero-desktop)', { lineHeight: 'var(--line-height-none)' }],
                'title-mobile': ['var(--font-size-title-mobile)', { lineHeight: 'var(--line-height-none)' }],
                'title-desktop': ['var(--font-size-title-desktop)', { lineHeight: 'var(--line-height-none)' }],
                'watermark-mobile': ['var(--font-size-watermark-mobile)', { lineHeight: 'var(--line-height-none)' }],
                'watermark-desktop': ['var(--font-size-watermark-desktop)', { lineHeight: 'var(--line-height-none)' }],
            },
            letterSpacing: {
                'tighter': 'var(--letter-spacing-tighter)',
                'tight': 'var(--letter-spacing-tight)',
                'normal': 'var(--letter-spacing-normal)',
                'wide': 'var(--letter-spacing-wide)',
                'wider': 'var(--letter-spacing-wider)',
                'widest': 'var(--letter-spacing-widest)',
                'extra': 'var(--letter-spacing-extra)',
                'ultra': 'var(--letter-spacing-ultra)',
                'max': 'var(--letter-spacing-max)',
            },
            fontWeight: {
                light: 'var(--font-weight-light)',
                normal: 'var(--font-weight-normal)',
                medium: 'var(--font-weight-medium)',
                semibold: 'var(--font-weight-semibold)',
                bold: 'var(--font-weight-bold)',
                extrabold: 'var(--font-weight-extrabold)',
                black: 'var(--font-weight-black)',
            },
            borderRadius: {
                none: '0',
                sm: 'var(--radius-sm)',
                md: 'var(--radius-md)',
                lg: 'var(--radius-lg)',
                full: 'var(--radius-full)',
                DEFAULT: 'var(--radius)',
            },
            zIndex: {
                'base': 'var(--z-base)',
                'dropdown': 'var(--z-dropdown)',
                'sticky': 'var(--z-sticky)',
                'fixed': 'var(--z-fixed)',
                'modal-backdrop': 'var(--z-modal-backdrop)',
                'modal': 'var(--z-modal)',
                'popover': 'var(--z-popover)',
                'tooltip': 'var(--z-tooltip)',
                'cursor': 'var(--z-cursor)',
                'header': 'var(--z-header)',
                'masthead': 'var(--z-masthead)',
                'drawer-backdrop': 'var(--z-drawer-backdrop)',
                'drawer': 'var(--z-drawer)',
                'drawer-button': 'var(--z-drawer-button)',
                'progress-bar': 'var(--z-progress-bar)',
            },
            opacity: {
                'disabled': 'var(--opacity-disabled)',
                'hover': 'var(--opacity-hover)',
                'overlay': 'var(--opacity-overlay)',
                'grain': 'var(--opacity-grain)',
                'watermark': 'var(--opacity-watermark)',
                'backdrop': 'var(--opacity-backdrop)',
            },
            transitionDuration: {
                'fast': 'var(--transition-fast)',
                'base': 'var(--transition-base)',
                'normal': 'var(--transition-normal)',
                'slow': 'var(--transition-slow)',
                'slower': 'var(--transition-slower)',
                'slowest': 'var(--transition-slowest)',
                'slowest-plus': 'var(--transition-slowest-plus)',
            },
            transitionTimingFunction: {
                'default': 'var(--ease-default)',
                'in': 'var(--ease-in)',
                'out': 'var(--ease-out)',
                'in-out': 'var(--ease-in-out)',
                'power2': 'var(--ease-power2)',
                'power3': 'var(--ease-power3)',
                'power4': 'var(--ease-power4)',
            },
        },
    },
};
